# Generated by Django 5.2.8 on 2026-03-16 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_alter_identity_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadata',
            name='accessibility',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('APPROVAL_NEEDED', 'Approval needed'), ('NOT_ACCESSIBLE', 'Not accessible'), ('INTERNAL', 'Internal')], default='PUBLIC', help_text="<li><b>Public</b>: data can be downloaded without restrictions.</li>\n<li><b>Approval needed</b>: The contact of this metadata with <i>is validator?</i> set\n  to true will have to validate this product for extraction</li>\n<li><b>Not accessible</b>: The metadata is public, everybody knows the data exists but it's\n  not possible to order it (unless you explicitly create a product).</li>\n<li><b>Internal</b>: The metadata is not published.</li>", max_length=30, verbose_name='accessibility'),
        ),
    ]
