# Generated by Django 5.2.13 on 2026-04-28 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_alter_identity_language_alter_metadata_accessibility_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchange',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='identity',
            name='language',
            field=models.CharField(choices=[('EN', 'English'), ('DE', 'German'), ('FR', 'French')], default='EN', max_length=10, null=True, verbose_name='language'),
        ),
    ]
