# Generated by Django 5.2.13 on 2026-05-04 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_userchange_date_created_alter_identity_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='validation_reason',
            field=models.CharField(blank=True, max_length=2048, null=True, verbose_name='validation_reason'),
        ),
        migrations.AlterField(
            model_name='userchange',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
