# Generated by Django 5.2.14 on 2026-05-26 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_orderitem_validation_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='use_largest_area_validation',
            field=models.BooleanField(default=False, help_text='If checked, validation is requested only from the DMO (data management office) having the largest area overlap with the requested perimeter.', verbose_name='use largest area validation'),
        ),
    ]
