# Generated by Django 5.2.14 on 2026-05-26 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_orderitem_validation_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadata',
            name='use_largest_area_validation',
            field=models.BooleanField(default=False, help_text='If checked, validation is requested only from the DMO (data management office) having the largest area overlap with the requested area.', verbose_name='use largest area validation'),
        ),
        migrations.AddField(
            model_name='pricinggeometry',
            name='validator',
            field=models.ForeignKey(blank=True, help_text='The DMO responsible for validation and invoicing in this area.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.contact', verbose_name='validator'),
        ),
        migrations.AlterField(
            model_name='product',
            name='max_order_area',
            field=models.IntegerField(default=0.0, verbose_name='max_order_area'),
        ),
    ]
