# Generated by Django 5.2.17 on 2026-09-18 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0061_alter_order_order_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='max_order_area',
            field=models.IntegerField(default=0.0, verbose_name='max_order_area'),
        ),
        migrations.CreateModel(
            name='ProductUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('product', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'product update',
                'db_table': 'product_update',
            },
        ),
    ]
