# Generated by Django 5.2.17 on 2026-09-17 11:07

from django.db import migrations


def insert_site_urls(apps, schema_editor):
    Site = apps.get_model('sites', 'Site')
    Site.objects.update_or_create(
        id=1,
        defaults={'domain': 'localhost:8000', 'name': 'localhost'}
    )
    Site.objects.update_or_create(
        id=2,
        defaults={'domain': 'geoshop-test.geogr.ch', 'name': 'geoshop-int'}
    )
    Site.objects.update_or_create(
        id=3,
        defaults={'domain': 'geoshop.geogr.ch', 'name': 'geoshop-prod'}
    )

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0062_alter_product_max_order_area_productupdate'),
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(insert_site_urls),
    ]
