name: Python unit tests

on:
  push:
  pull_request:
  workflow_call:

jobs:
  tests:
    name: Execute unit tests
    concurrency: ci-${{ github.ref }}
    strategy:
      matrix:
        python-version: [3.12]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade pip version
        run: |
          python -m pip install -U pip

      - run: echo "${HOME}/.local/bin" >> ${GITHUB_PATH}

      - name: Install CI dependencies
        run: python3 -m pip install --user --requirement=ci/requirements.txt

      - name: Environment information
        run: c2cciutils-env
        env:
          GITHUB_EVENT: ${{ toJson(github) }}

      - name: Copy .env file
        run: cp .env.sample .env

      - name: Prepare Docker images and start Compose environment
        run: make prepare_env

      - name: Run tests
        run: make test

      - name: Docker logs
        run: c2cciutils-docker-logs

      - name: Stop Compose environment
        run: make destroy_env
